### ISSUE TITLE
Changing Profile images.

### ISSUE THREAD

**Issue by CarePackageUK** [andyngo/conversable-for-scriptable#1]
Hi there, I've noticed a problem when switching the profile pictures to other pictures. I've been using .PNG files like usual, even tried with the same names (1,2,3,4) but I'm having no luck. when i change them to the new images they disappear off the widget.

Any help would be appreciated, also great work, i love it.

**Comment by CarePackageUK** [comment]
As you can see from the pictures

![EBC20FF8-BA60-4CB3-92EB-250E569693A9](https://user-images.githubusercontent.com/72028668/95366982-172b5b00-08cc-11eb-9bb6-76c85391615b.png)
![3FFAB4CA-B3B3-4172-9B1E-57251AFBBA6F](https://user-images.githubusercontent.com/72028668/95366989-185c8800-08cc-11eb-8b41-a0d91acfd0df.png)

**Comment by andyngo** [comment]
@CarePackageUK Hi, could you check if you've added .PNG to the end of the filename in the Conversable folder? If you did, you should remove the .PNG extension. iCloud Drive seems to hide file extensions by default and I'm not sure if there's a way to change this. This could end up adding an extra .PNG (1.PNG.PNG) to your file, which may have caused the issue.

**Comment by CarePackageUK** [comment]
Thank you for getting back to me, yeh there's no .PNG at the end of the name, only as a file type.

**Comment by CarePackageUK** [comment]
![image](https://user-images.githubusercontent.com/72028668/95403590-8de74900-090a-11eb-9908-3f476efeedaf.jpeg)

**Comment by andyngo** [comment]
@CarePackageUK That's odd. Your files seem to be stuck at 'Waiting…' which may indicate that it's not uploading to iCloud. I'm not sure if this is directly connected to your issue.

Could you try adding adding `console.log(isDownloaded)` like so, and run the script? Dismiss the Widget preview and click on the console (the one with [8] in the picture below).
![image](https://user-images.githubusercontent.com/278293/95404106-b55c0700-0946-11eb-8eb6-a8f6c69fbd24.jpeg)

There should be some message printed there.

**Comment by CarePackageUK** [comment]
That might be the problem (iCloud download part) as I only 4 true.
You know how to make the files download to iCloud faster?

**Comment by andyngo** [comment]
@CarePackageUK I'm not so sure, the files shouldn't take too long to download assuming that they're not that big in size. Toggling your iCloud Drive on/off in Settings might work but proceed at your own risk. Or simply toggle Airplane mode to see if it forces the file to start uploading.

One more thing: could you add this code `console.log(fm.fileExists(path))` and show me the output?

**Comment by CarePackageUK** [comment]
Got all true
![image](https://user-images.githubusercontent.com/72028668/95405640-495eac00-0910-11eb-81fa-ed583c2bacf8.png)

**Comment by CarePackageUK** [comment]
Just did airplane mode and the files all download and now works. Thank you

**Comment by andyngo** [comment]
@CarePackageUK Glad you got it to work! Enjoy the widget. :)

**Comment by andyngo** [comment]
Closing this as the issue seems to have been resolved. Feel free to reopen if the issue arises again.
