### ISSUE TITLE
Contact Name

### ISSUE THREAD

**Issue by TankeAguilar** [andyngo/conversable-for-scriptable#3]
![image](https://user-images.githubusercontent.com/72666564/95662926-3c081400-0b00-11eb-8bf0-cabe74c04b91.png)
Only appears the image, but no the contact name.

I love the script, thanks for your contribution!

**Comment by andyngo** [comment]
Issue resolved: turns out the issue here was the naming of the “icons” folder. Instead of “icons” (all lowercase), Tanke had named them “Icons” instead (uppercase i) therefore causing the whole row to not be displayed.
