### ISSUE TITLE
Text in Light Mode is not Visible

### ISSUE THREAD

**Issue by wild-a** [andyngo/conversable-for-scriptable#6]
Text in light mode is black on a dark background (so not visible), but works fine in dark mode (white text on dark background).
![85544FAE-E5D8-430D-A6F7-67DBF8ACF35D](https://user-images.githubusercontent.com/74679016/99574212-ad0ed700-299c-11eb-85ad-1db18a989248.jpeg)

**Comment by wild-a** [comment]
Setting background using Color.dynamic allows for setting separate dark mode and light mode background colors.

**Comment by wdkevonfernando** [comment]
I have made a pull request #7 that fixes this issue like you did with support for settings.
